### PR TITLE
Add Prime Mini Wireless support.

### PR DESCRIPTION
**Pull request by intersectRaven**
Solves #207.

### CODE REVIEW

**Comment by flozz** [comment]
Hello,

Can you answer to this comment in the issue ?

https://github.com/flozz/rivalcfg/issues/207#issuecomment-1681725983

**Comment by intersectRaven** [comment]
I don't know why the checks are failing. :(

**Comment by flozz** [comment]
The errors in the checks are not related with your PR. It seems Flake8 found new issues that it was not able to detect before... I should probably fix its version to avoid this kind of problem.

Anyway I will look at this later today, it will not block the merge of your PR :)

**Comment by flozz** [comment]
Thank you for the PR. The support of this device will be available with next Rivalcfg release :)

**Pull request merged**
