### PR TITLE
Add support for SteelSeries Rival 105

### PR DESCRIPTION
**Pull request by vonsowic**
Commands of SteelSeries 100 work for this model, but options --btn6-action and --sensitivity2 seems to have no effect

### CODE REVIEW

**Comment by flozz** [comment]
Hello,

----

to test if `btn6-action` works, please try the following:

1. Set it to `default`:

    rivalcfg -b default

2. Run xev:

    xev

3. Click on the xev window with the button no 6 on the mouse (the one under the wheel). → Nothing should happen.

4. Now set the option to `os`: 

    rivalcfg -b os

5. Click again on the xev window with the button. Now you should see logs like this in the console:

```
ButtonPress event, serial 34, synthetic NO, window 0x4400001,
    root 0x2b0, subw 0x0, time 62290069, (169,175), root:(2177,327),
    state 0x0, button 10, same_screen YES

ButtonRelease event, serial 34, synthetic NO, window 0x4400001,
    root 0x2b0, subw 0x0, time 62291631, (169,175), root:(2177,327),
    state 0x0, button 10, same_screen YES
```

(here my X11 recognize the button as `button 10`)

------

To check if sensitivity 2 work, set the lower sensitivity on the first preset, and the higher sensibility on the second one. You will have to set the `btn6` action to default too:

    rivalcfg -b default -s 200 -S 7200

Now move the mouse cursor, then press the btn6 (the button under the wheel) and move again. The speed of the cursor moves should change 

------

Can you confirm that it works? :)

**Comment by vonsowic** [comment]
Everything proceeded as you expected :) the only difference I made was to change options to `rivalcfg -b default -s 250 -S 4000`. Thanks for your help with testing

**Comment by flozz** [comment]
Ok, thank you, I will review the PR tomorrow and release a new rivalcfg version once merged :D

**Comment by flozz** [comment]
Hum I have a question, you changed the options because the sensitivity is from 250 to 4000 on this mouse ?

**Comment by vonsowic** [comment]
Actually I changed it because I got an error `rivalcfg: error: option -s: invalid choice: '200' (choose from '250', '500', '1000', '1250', '1500', '1750', '2000', '4000')` :) but sensitivity of this mouse is 4000DPI, so I guess it is ok? Lower sensitivities I'll try to test in the evening.

**Comment by flozz** [comment]
thanks for the PR !

I will release a new version this weekend  :)

**Comment by flozz** [comment]
Released in **rivalcfg v3.9.0** :)

**Pull request merged**
