### PR TITLE
LED support for sensei 310

### PR DESCRIPTION
**Pull request by Gazler**
Currently still a work in progress. The LED settings definitely work, I
am still trying to work out the exact spec.

This isn't ready for merging yet, I am just opening it for discussion in case anyone else is working on it.

### CODE REVIEW

**Comment by flozz** [comment]
Ok, thank you, let me know when it is ready :)

**Comment by Gazler** [comment]
Weirdly, although the color commands work (`0x07, 0x02, 0x01, 0xRR, 0xGG, 0xBB`) - it is not even close to what I found in Wireshark.

Here's a dump for setting the mouse wheel LED to #FF5200

```
0000   5b 00 01 bc 07 00 00 00 00 00 00 00 00 00 00 01
0010   00 01 00 01 00 00 00 00 00 00 00 01 ff 52 00 ff
0020   52 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0030   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0070   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0080   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0100   00 00 00 00 00 00
```

Maybe they have a new command which always sets it as a color cycle, since here is the output from a color cycle for the mousewheel LED using "ColorShift" at speed 1.33 for the following colors:

 * 00% - `#00ff91`
 * 33% - `#ffea00`
 * 66% - `#00ccff`

```
0000   5b 00 01 bc 07 00 00 00 00 00 00 00 00 00 00 01
0010   00 01 00 00 00 00 00 00 00 00 00 04 00 ff 91 00
0020   ff 91 00 ff ea 00 54 00 cc ff 54 00 ff 91 56 00
0030   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0070   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0080   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0100   00 00 00 00 00 00
```

**Comment by Gazler** [comment]
For completion

Here's a dump for setting the logo LED to `#ff5200`

```
0000   5b 00 00 bc 07 00 00 00 00 00 00 00 00 00 00 01
0010   00 01 00 01 00 00 00 00 00 00 00 01 ff 52 00 ff
0020   52 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0030   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0070   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0080   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0100   00 00 00 00 00 00
```

So it looks like `5b` is the command `00` is ignored, then `00` is the led. That's about as far as I have managed to get. The color is there in there at position `0016`, and again at position `0019`. Perhaps the `01` at `0015` is the mode?

**Comment by Gazler** [comment]
I've figured out the timings. It is in little endian. Here's the conversions for the timing above:

```
+------+---------------+---------------------+--------------------------------+
| HEX  | LITTLE ENDIAN |       BINARY        |            DECIMAL             |
+------+---------------+---------------------+--------------------------------+
|      |               |                     |                                |
| bc07 | 07bc          | 1100 0110 0000 0111 | 1.98s*                         |
|      |               |                     |                                |
| aa0a | aa0a          | 0000 1010 1010 1010 | 2.73s                          |
|      |               |                     |                                |
| 8813 | 1388          | 0001 0011 1000 1000 | 5.00s                          |
|      |               |                     |                                |
| 6851 | 5168          | 0101 0001 0110 1000 | 20.84s                         |
+------+---------------+---------------------+--------------------------------+

* Note this is the min value which is why we were seeing it for 1.33s
```

**Comment by flozz** [comment]
I think this will also help to understand how rival 500 and 700 (and 310?) work too :D

**Comment by Gazler** [comment]
I have made a little more progress with how the percentages are represented.

```
00%: 32ff91
06%: ffea0a
66%: 1eccff
81%: 632427
89%: 5af3ab

Position 1c: color 1
Position 1f: color 1
Position 23: color 2
Position 27: color 3
Position 2b: color 4
Position 2f: color 5
Position 33: color 1

       00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f

0000   5b 00 00 e4 0c 00 00 00 00 00 00 00 00 00 00 01
0010   00 01 00 00 00 00 00 00 00 00 00 06 32 ff 91 32
0020   ff 91 00 ff ea 0a 0f 1e cc ff 99 63 24 27 26 5a
0030   f3 ab 14 32 ff 91 1c 00 00 00 00 00 00 00 00 00
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0050   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0060   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0070   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0080   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0090   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00a0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00b0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00c0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00d0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00e0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00f0   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0100   00 00 00 00 00 00

[111111] [111111]    [222222]    [333333]    [444444]    [555555]    [111111]
32 ff 91 32 ff 91 00 ff ea 0a 0f 1e cc ff 99 63 24 27 26 5a f3 ab 14 32 ff 91 1c

Colors - start color repeated 3 times. Each other color once. The number dividing the colors represents a percentage of 255. e.g:

 * 0x0f: 15 / 255  = ~0.06 = 6%
                      Total: 6%
 * 0x99: 153 / 255 = ~0.60 = 60%
                      Total: 66%
 * 0x26: 38 / 255  = ~0.15 = 15%
                      Total: 81%
 * 0x14: 20 / 255  = ~0.08 = 8%
                      Total: 89%
 * 0x1c: 28 / 255  = ~0.11 = 100%
```

The first color is repeated 3 times. My best guess is that this represents the start and end color.

**Comment by ahstro** [comment]
Does this only apply to the Sensei 310 or would it also work for the Rival 310? My untrained mind would assume them to have the same internals, but I'm not going to pretend that I know how this works at all.

**Comment by Gazler** [comment]
@ahstro If you have a Rival 310, feel free to try the following:

This should turn the mouse wheel LED orange

```
echo -en "\x5b\x00\x01\xbc\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\xff\x52\x00\xff\x52\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" > /dev/hidraw6
```

This should cycle between blue, green and yellow.
```
echo -en "\x5b\x00\x01\xbc\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\xff\x91\x00\xff\x91\x00\xff\xea\x00\x54\x00\xcc\xff\x54\x00\xff\x91\x56\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" > /dev/hidraw6
```

Please note, you may need to try a different device id, it was 6 in my case.


If it works then we can probably assume that they use the same protocol.

**Comment by ahstro** [comment]
@Gazler It doesn't seem to do anything, unfortunately, but thank you for trying to help 🙂

**Comment by mikeshultz** [comment]
Just picked up a Sensei 310(`1038:1722`).  Your command to turn the mouse wheel LED off worked, but the ones to to change the mouse wheel color do not.  Actually, it just set the device back to it's default multi-color fade mode.  

I'm no good at reverse engineering this stuff, but let me know if you need any testing.

**Comment by Gazler** [comment]
@mikeshultz That's bizarre. I just tried the one to set the mouse LED to orange and it definitely worked (I had to change the `/dev/hidraw6` to match my device. 

The command to turn the LED off is totally different to the others (I copied it from the config for a different model.) Interestingly, the command to turn the mouse wheel LED orange also turned on the other LED, maybe the LED off command sets it in a different mode.

What OS are you on?

**Comment by mikeshultz** [comment]
Ubuntu Linux 17.10.  Linux 4.13.0-19-generic x86_64.  

Perhaps for the color setting to work I have to get out of this original cycle mode?  I have not yet hooked this up to a windows machine to change any settings, so it's just cycling/fading through all the colors.

**Comment by FFY00** [comment]
I tested this changes with my Rival 310 and they're partially working.

Problems I've seen so far:
  * The light effects don't work as intended. They always set the mouse to color fade with the same velocity. The velocity of the wheel is superior to the velocity of the logo.
  * The wheel and the logo aren't synchronized when they're both in color fade mode.

**Comment by flozz** [comment]
If someone can publish a fix for the light effect I will be happy to merge this PR, else, if the majority of the mouse options work, I can merge it as experimental support :)

**Comment by FFY00** [comment]
@flozz I will work on that.

**Comment by FFY00** [comment]
I've figured out the colors.

The breathing cycle is divided in 254 iterations (idk what to call them). You have several points and the delay between them

It goes like this
```
POINT -> DELAY -> POINT -> DELAY -> POINT -> DELAY -> POINT -> DELAY
```

You can it here.
re-mouse

**Comment by FFY00** [comment]
Okay. I figured out why there were two points with a position offset of `0`. The program automatically adds them to make sure the last point fades with the first. In the example above I forced the last point to the position `100%` so the space between the last user defined point and the last real point is `0` (see **(2)**).



re2

**Comment by FFY00** [comment]
Whit this say, let me point out that there are no `steady` or `breath` modes. There are only 2 modes, `colorshift` (both `steady` and `breath` modes use this) and `trigger`.

Here's an example of the `trigger` mode.
trigger

The brown bytes appear to be the mode command.

We can see again the points. At `00` we have `3151ff`, and at `FF` we have `ff1800`.
It seems like the cycle freezes at `FF` and only starts again when a button is clicked. That's why the normal color is the last and the color when triggered is the first.

**Comment by FFY00** [comment]
@flozz can you explain me how the project is structured so I can implement the commands? I am familiar with the structure but I have no idea how do I customize the packet itself.

**Comment by flozz** [comment]
Hi,

* For the CLI, you will have to add a `_add_<TYPE>_option` in `cli.py`,
* and to craft the packet data, you will have to implement an handler in `command_handler.py`. I think the best point to start reading to have more information is here → https://github.com/flozz/rivalcfg/blob/master/rivalcfg/mouse.py#L60 .

**Comment by FFY00** [comment]
Full specification of the `5B` command.

**(0) Specification**
Byte (Index) | Explanation | Values
:---: | :---: | :---:
0 | Command | `5B`
1 | Unknown | `00`
2 | Led ID | See **(1)**
3-4 | Cycle Duration | 1.98s to 32s (need to comfirm)
5-18 | Unknown | `00`
19 | Repeat Cycle | See **(2)** 
20-22 | Unknown | `00`
23 | Trigger Buttons | See **(3)**
24-26 |  Unknown | `00`
27 | Number of points | Hex int
28-30 | Fallback Color? | First color in the cycle. `RR GG BB`
31-End | Points | Color and Position offset `RR GG BB 00` (`00` is the position offset)

**(1) Led ID**
Value | Led
:---: | :---:
`00` | Logo
`01` | Wheel

**(2) Repeat Cycle**
Value | Translation | Explanation
:---: | :---: | :---:
`00` | Doesn't repeat | When the cycle ends, it will restart again.
`01` | Repeat | When the cycle ends (`tick = 255`), it will restart (`tick` will be set to `0`).

**Note** The cycle is defined later in the format of points. The cycle has a duration of 255 ticks. You can define points. Points are defined as the following:

```
Color |  Position Offset (how many ticks after the last defined point)
```

**(3) Trigger**
This is actually very simple. When one of the selected buttons is clicked, the cycle will start again (`tick` will be set to `0`).
```
Bit Number | 87654321
Bits             | 00000000
```

Bit Number (see above) | Button
:---: | :---:
1 | Left
2 | Right
3 | Wheel Click
4 | Back (side)
5 | Forward (side)
6| DPI Switch
7-8 | Ignored

Examples:

Buttons | Binary Value | Hex Value
Left + Right + DPI Switch (default from the official driver) | `00000111` | `07`
Wheel Click + Forward | `00010100` | `14`
Left + Right + Back + Forward | `00011011` | `1B`
All | `00111111` | `3F`

**Comment by flozz** [comment]
I think this will be very helpful: Rival 500 and 700 have similar commands maybe this will help on those models too :)

**Comment by Gazler** [comment]
@FFY00 Thanks for sharing your findings! Very interesting.

**Comment by ozdemirburak** [comment]
I'll just leave this for the complete starters like me looking for a temporary solution. 

To find out which hidraw device your mouse is using, run the Python script mentioned [here](https://github.com/flozz/rivalcfg/issues/2), but modify the last line, product id for me was 1722.

    print(find_hidraw_device_path("1038", "1722", 0))

If you still get the `None` output, then check your product id from the kernel output.

    dmesg | grep SteelSeries
    >   hid-generic 0003:_1038_:********1722********.000E: 

To change the LED to `#3151ff` as steady color, with following the instructions [here](https://github.com/flozz/rivalcfg/pull/43#issuecomment-375988246), first if you are not root run the `sudo -i`, then run the code below, but do not forget to change the hidraw number.

    echo -en "\x5b\x00\x00\x88\x13\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x31\x51\xff\x31\x51\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" > /dev/hidraw1

Let's say if you want to change the `#3151ff` to `#333333`, then just change the parts in the code snippet  above, `\x31\x51\xff\x31\x51\xff` with `\x33\x33\x33\x33\x33\x33`.

**Comment by FFY00** [comment]
@ozdemirburak, you can use the code in this PR. It's working, I actually don't know why it wasn't been merged yet.

**Comment by flozz** [comment]
@FFY00  It is not merged because of lack of time on my side... I have to review it and merge it but I have no time currently ^^'

**Comment by FFY00** [comment]
No problem! I was just wondering.

**Comment by ergor** [comment]
Very well written analysis, @FFY00!

I have added support for this type of color protocol in pr #60, as the Rival600 and this mouse share many similarities. It should be easy to configure this mouse for steady, shifting and trigger mode support with the new value type I added.

**Comment by flozz** [comment]
I will review this PR once the #60 is merged. maybe I will have to adapt it to match the work of #60. I will need someone to check everything work then :)

**Comment by Alexiwnl** [comment]
I would love some help at #73

**Comment by GreenGas48** [comment]
@Gazler I have tested the commands you have posted on my SteelSeries Rival 310 and they fully work! I have it under /dev/hidraw6 just as you do.

**Comment by Besfr** [comment]
I can confirm that the command from https://github.com/flozz/rivalcfg/pull/43#issuecomment-406647564 works well with a rival 310.
I'm under debian 9.

**Comment by mfs** [comment]
Great work. I have tested this branch on my new Sensei 310 and logo/wheel color setting and mode setting work great. Factor reset also works. (Python 3, Arch Linux)

**Comment by Baxtex** [comment]
> Great work. I have tested this branch on my new Sensei 310 and logo/wheel color setting and mode setting work great. Factor reset also works. (Python 3, Arch Linux)

Hmm what commands did you use? I just checked out this branch and installed it. All my commands result in 

```
rivalcfg --logo-color=black --wheel-color=black

W: The following mouse was found but rivalcfg was not able to open it:
  * mouse: SteelSeries Sensei 310 (Experimental) (1038:1722)
  * error: open failed

Please check that no other application is controlling this mouse and try to:
  * unplug the mouse from the USB port,
  * wait few seconds,
  * and plug the mouse to the USB port again.

Usage: rivalcfg [options]

rivalcfg: error: no such option: --logo-color

```

**Comment by mfs** [comment]
Did you install the udev rules in this branch? I did that manually. That should fix your permissions issue.

**Comment by Baxtex** [comment]
> Did you install the udev rules in this branch? I did that manually. That should fix your permissions issue.

Thanks, that worked!

**Comment by marco44** [comment]
Worked great for me too. Please merge :)

**Comment by FFY00** [comment]
@flozz I would like to advise against merging this in the current state. It uses the old commands from other mice, they are probably leftover code from forking the firmware for the Rival 310 and thus probably not tested. We should be using the same commands as the official windows driver.

https://github.com/flozz/rivalcfg/commit/da033b239e51f71c0a2a56199bf8a18d64c954a1 is a good start for a proper implementation

**Comment by flozz** [comment]
@FFY00 on the Sensei 310, the Windows driver seems to use exactly the same commands that the one in this PR

**Comment by flozz** [comment]
@FFY00 (after looking at the code) It is the same command that the one you described in the discussion of this PR , it is different than the one in the code :)

**Comment by FFY00** [comment]
Yeah, I thought so, but wanted to confirm. I was thinking it was maybe different versions or something.

**Comment by FFY00** [comment]
Btw, if you want to implement it yourself, I've emulated the mouse in software (intended to be used for CI). The code is here: https://github.com/libratbag/ratbag-emu/blob/master/ratbag_emu/protocol/steelseries.py (please disregard the bad code).

**Comment by flozz** [comment]
@FFY00 it will probably be very useful. I tried to make one myself when I started to work on this project but it never worked ^^'

**Comment by flozz** [comment]
Initial support of this mouse has been released in **rivalcfg v3.8.0** 😁️

**Pull request closed without merging**
