### PR TITLE
Added Rival 110 support

### PR DESCRIPTION
**Pull request by runfalk**
We had a go at making the Rival 110 work. It turned out to be fairly close to the 100, but the commands needs trailing null bytes to a certain length. The biggest difference is the wide array of DPI settings available.

### CODE REVIEW

**Comment by flozz** [comment]
Hi,

The DPI setting looks close to the Rival/Rival 300 one (https://github.com/flozz/rivalcfg/blob/master/rivalcfg/profiles/rival.py#L16-L19) but I cannot explain the inconsistent gap in the list:
```
200: 0x04,
300: 0x06,
400: 0x08,

→ +100: +2
```

```
400: 0x08,
500: 0x0b,

→ +100: +3
```

**Comment by flozz** [comment]
Merged, thank you for your contribution :)

**Comment by runfalk** [comment]
Thank you!

Yeah, the 2/3 jumps are a bit confusing. You can probably use the same function that the 300 uses and no-one will notice :). When I saw the jumps were inconsistent I figured it was better to just sniff the values for every selectable DPI in the SteelSeries Engine. So, hence the big list.

**Comment by ag88** [comment]
hi thanks ! it works (in linux) :)

**Pull request merged**
