### PR TITLE
Add tactile feedback command [WIP]

### PR DESCRIPTION
**Pull request by nixtux**
Add another feature from SSE, tactile feedback per mouse button

### CODE REVIEW

**Comment by flozz** [comment]
Why did you close it? :)

**Comment by nixtux** [comment]
Sorry was going to redo all tactile names inline with sse names and re open it.

**Comment by flozz** [comment]
No problem, if you think your PR is not ready yet, you can just add `[WIP]` (Work In Progress) in its name, so I know I should not merge it. But this allow us to discus if you need some help or have any question ;)

**Comment by nixtux** [comment]
Here is a link of settings in sse, https://imgur.com/BGLEE9n.png

**Pull request closed without merging**
