### PR TITLE
add suport for the SteelSeries Rival 310 eSports Mouse

### PR DESCRIPTION
**Pull request by tomheady**
Hi, I have added support for the Rival 310.

Thanks!

### CODE REVIEW

**Comment by DelusionalLogic** [comment]
Yeah, this doesn't work. Running it just crashes the mouse (It freezes)

**Comment by tomheady** [comment]
I was able to turn off the lights on my mouse.  Which options did you give?

**Comment by DelusionalLogic** [comment]
$ rivalcfg --sensitivity2=800

Running it either crashes the mouse or messes up my color scheme

Another thing to note is that the rival 310 supports up to 12000 dpi, which makes the rival config wrong regardless.

**Comment by tomheady** [comment]
ah, ok.  I now notice you have an earlier pull request that goes deeper than mine.  If you also take the changes to readme.md I will discard this merge request.

**Comment by DelusionalLogic** [comment]
You should probably close this pullrequest now, given that it just softbricked the lighting controller in my mouse.

**Comment by flozz** [comment]
Even if this PR will not be merged, thank you for your help and for your interest about this project :)

**Pull request closed without merging**
