### PR TITLE
Return the number of bytes written from all mouse commands

### PR DESCRIPTION
**Pull request by Demon000**
This would be useful to check if the command was actually completed successfully.

### CODE REVIEW

**Comment by Demon000** [comment]
We could also throw an exception on failure but that might break stuff for some people I guess.

**Comment by Demon000** [comment]
I'm using this like this https://github.com/Demon000/rivalcolor/blob/master/rival.py#L55 to make sure that the command was successful and try to reconnect to the mouse if not.

**Comment by flozz** [comment]
Hi, it is ok for me to return the written bytes count, thank you :)

**Comment by Demon000** [comment]
Thanks a lot.

**Comment by flozz** [comment]
→ Released in **rivalcfg 3.6.0** :)

**Pull request merged**
