### PR TITLE
Add support for Steelseries Rival Dota 2 Edition

### PR DESCRIPTION
**Pull request by virrim**

### CODE REVIEW

**Comment by flozz** [comment]
Hello,

Thank you for your PR, there is some issues that must be fixed before I can merge it :) :

* Can you please rename the `rivalcfg/profiles/rivaldota` to `rivalcfg/profiles/rivaldota2.py` (it does not work without the `.py` extension)

* Also, if it has the same instruction set than the Rival mouse, can you include commands from this file instead of copying its content (like in the `rival300.py` profile → https://github.com/flozz/rivalcfg/blob/master/rivalcfg/profiles/rival300.py)

Thank you again for your PR, I hope I will be able to merge it soon to add it in the next release! :)

**Comment by flozz** [comment]
Hi, I forgot it in my last review but you must add your mouse in this file too:

https://github.com/flozz/rivalcfg/blob/master/rivalcfg/data/99-steelseries-rival.rules

:)

**Comment by flozz** [comment]
Thank you very much, for the PR, I will release this soon :)

**Comment by flozz** [comment]
Hum, I have a question, is it this one

* https://www.ldlc.com/fiche/PB00183592.html

or this one 

* https://www.ldlc.com/fiche/PB00217133.html

?

**Comment by virrim** [comment]
It is the former (Rival 300)

**Comment by flozz** [comment]
Released in **v3.2.0** :)

**Pull request merged**
